### ISSUE TITLE
Iterations per chain

### ISSUE THREAD

**Issue by mattmoo** [lindeloev/mcp#113]
The documentation states:
```
#' @param iter Positive integer. Number of post-warmup samples to draw. The number
#'   of iterations per chain is `iter/chains`.
```

However, looking in the `mcpfit` object, I see `chains` tables in each of the `mcmc_*` fields, each with `iter` rows. Is there a reason why I would not expect each to have `iter/chains` rows?

**Comment by lindeloev** [comment]
Thanks! This is an error in the documentation. `mcp` tries to stay close to [`brms` defaults](https://www.rdocumentation.org/packages/brms/versions/2.14.4/topics/brm)
