### ISSUE TITLE
Cross-validation Bayes Factor

### ISSUE THREAD

**Issue by MZelko82** [lindeloev/mcp#122]
Given you have hypothesis testing via Bayes Factors as well as LOO-CV, would a prior-free BF using CV be useful?

Hart, Jeffrey D., and Matthew Malloure. "Prior‐free Bayes Factors Based on Data Splitting." International Statistical Review 87.2 (2019): 419-442. doi:10.1111/insr.12323

**Comment by lindeloev** [comment]
Thanks for submitting this idea! `mcp` currently uses JAGS as sampler. JAGS does not allow improper priors, including no prior (corresponding to an infinite flat prior). With the planned support for `stan` (#100), this will become an option, but this is 1-2 years into the future from now. I'm adding it to the worklist there and closing this for now.
