### ISSUE TITLE
Cran fix?

### ISSUE THREAD

**Issue by multimeric** [lindeloev/mcp#123]
Hi, it looks like `mcp` got pulled off CRAN: https://cran.r-project.org/web/packages/mcp/index.html. Any chance this could be looked into?

**Comment by jw5** [comment]
I'm hoping that the CRAN built version is updated for the current version of R. 

In the meantime, a workaround is to install mcp from the github repository as shown on the main page:

if (!requireNamespace("remotes")) install.packages("remotes")
remotes::install_github("lindeloev/mcp")

**Comment by lindeloev** [comment]
Yeah, I'm just swamped right now but will return to mcp soon! The next release is 90% done. So install_github() until then.

**Comment by lindeloev** [comment]
v0.3.1 is in the master branch and on it's way to CRAN review now. Should fix this.
