### ISSUE TITLE
default code plot doesn't work, looks like code compatibility problem

### ISSUE THREAD

**Issue by m-r-munroe** [lindeloev/mcp#127]
I tried to run this code;

```
library(mcp)

# Define the model
model = list(
  response ~ 1,  # plateau (int_1)
  ~ 0 + time,    # joined slope (time_2) at cp_1
  ~ 1 + time     # disjoined slope (int_3, time_3) at cp_2
)

# Get example data and fit it
ex = mcp_example("demo")
fit = mcp(model, data = ex$data)

plot(fit)
```

It returned this:

```
> fit = mcp(model, data = ex$data)
Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 100
   Unobserved stochastic nodes: 7
   Total graph size: 1732

Initializing model

  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
  |**************************************************| 100%
Finished sampling in 8.6 seconds

> plot(fit)
Error in tidy_draws.default(.) : 
  Don't know how to convert an object of class "list"
into a tidy data frame of draws. See help("tidybayes-models") for a list
of models supported by tidy_draws()
```

To my (uninformed) eye it looks like it ran properly, but the structure of the object that it tried to plot isn't working with the JAGS code.  

So then I try to print the summary, and I get this:

```
> summary(fit)
Family: gaussian(link = 'identity')
Iterations: 9000 from 3 chains.
Segments:
  1: response ~ 1
  2: response ~ 1 ~ 0 + time
  3: response ~ 1 ~ 1 + time

Population-level parameters:
Error in tidy_draws.default(.) : 
  Don't know how to convert an object of class "list"
into a tidy data frame of draws. See help("tidybayes-models") for a list
of models supported by tidy_draws().
```
UPDATE:
I tried uninstalling jags 4.3.0 and installing 4.2.0 but the version of JAGS doesn't change the output.

UPDATE 2:
I tried running other example code:

```
model = list(
  y ~ 1 + x,          # intercept + slope
  1 + (1|id) ~ 0 + x  # joined slope, varying by id
)
ex = mcp_example("varying")
fit = mcp(model, ex$data)
plot(fit, facet_by = "id")
```

And it plotted, while giving a warning related to deprecated alieses in tidybayes.

```
> plot(fit, facet_by = "id")
Warning messages:
1: 
In tidybayes::spread_draws(): The `n` argument is a deprecated alias for `ndraws`.
Use the `ndraws` argument instead.
See help("tidybayes-deprecated").
 
2: 
In tidybayes::spread_draws(): The `n` argument is a deprecated alias for `ndraws`.
Use the `ndraws` argument instead.
See help("tidybayes-deprecated").
```

**Comment by byzheng** [comment]
This error is fixed in the pull request: https://github.com/lindeloev/mcp/pull/126

**Comment by lindeloev** [comment]
Thank you for reporting, @m-r-munroe, and for the PR, @byzheng! Yes, it seems that `{tidybayes}` has deprecated something. I'm hoping I remove that dependency (`{coda}` too) and move to the new `{posterior}`. I'll see how far I can get or whether I should publish an interim bugfix release.

**Comment by mschubert** [comment]
I'm getting the same error even after downgrading `tidybayes`.

**Comment by m-r-munroe** [comment]
When I go "update packages" in Rstudio, tidybayes is not on the list. I'm updating all anyway.
Then I uninstall and reinstall both mcp and tidybayes.  

code to load:
`require(pacman)

p_load(tidyverse,    #lots of tools
       here,         # file indexing
       ggplot2,      # making plots
       tidybayes)
p_load_gh("lindeloev/mcp")`

Result:
![image](https://user-images.githubusercontent.com/19671526/142022983-e983edde-c662-4cc6-bbb1-dc40441c96ba.png)

And when I run the example code, I get these two:
![image](https://user-images.githubusercontent.com/19671526/142023299-b7eea5dc-a63a-4ac8-b67e-b7d7fe354776.png)
and
![image](https://user-images.githubusercontent.com/19671526/142023351-659d5a0c-6906-4f2c-8d0a-b0ed9010caa3.png)

**Comment by lindeloev** [comment]
That's a relief. Thanks for letting us know!
