### ISSUE TITLE
parallel option "all" not working

### ISSUE THREAD

**Issue by m-r-munroe** [lindeloev/mcp#131]
Code:
```
fit = mcp(model, 
          data = df,
          cores = "all")
```

All option was used per help option:
```
cores	Positive integer or "all". Number of cores.
"all": use all cores but one and sets chains to the same value. This is a convenient way to maximally use your computer's power.
```

Expected it to run, but instead it gave error.

Error:
![image](https://user-images.githubusercontent.com/19671526/142453087-5d6212c7-43d7-4127-b62f-826d6cd3c2df.png)

**Comment by lindeloev** [comment]
Thanks for reporting. I submitted a fix to the v0.4 branch, i.e., the next version.
