### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Graham-Rush** [lindeloev/mcp#145]
Hi, 
I get the following error if I try to do anything in mcp
'Error in is.type(x) : object 'ffi_is_formula' not found'
Could you advise on the solution please?

**Comment by Graham-Rush** [comment]
I have now fixed this by updating 'rlang'

**Comment by lindeloev** [comment]
Thanks, I'll keep this in mind if it pops up again! There are several braking changes in the latest tidyverse packages, so I hope the error arises between them - not from mcp.
