### ISSUE TITLE
object ffi_is_formula not found

### ISSUE THREAD

**Issue by ShiyanYang** [lindeloev/mcp#153]
I try to run the example provided in **mcp: Regression with Multiple Change Points**. But the error shows:
Erro in is.type(x): object 'ffi_is_formula' not found.

Could you help me to debug this issue? Thank you!

**Comment by lindeloev** [comment]
This looks like an error in `rlang`. Could you try to update it to the latest version, restart the session, and see if the issue persists? `install.packages("rlang")`.

`ffi_is_formula` is called from `rlang::is_formula()` which is called from `mcp`. It's source code is here: https://github.com/r-lib/rlang/blob/main/R/formula.R

**Comment by lindeloev** [comment]
I see now that this was also reported in #145 and fixed by updating `rlang` (as I suspected above). I'm closing this for now.
