### ISSUE TITLE
Exponent bug

### ISSUE THREAD

**Issue by isomemo** [lindeloev/mcp#159]
@lindeloev tried the power function I(x^1.5) example as per the "Quadratic and other exponentiations" section of the mcp vignette. Issued error:

Error in assert_integer(as.numeric(exponent), term, lower = 0) : 
  Only integers >= 0 allowed for 'x^1.5'. Got 1.5

Extra note: would be useful to also include negative exponents.

**Comment by lindeloev** [comment]
@isomemo mcp compiles a JAGS model and JAGS only allows integers in the exponent. At least when x is negative. See page page number 26 in [the JAGS manual](https://www.uvm.edu/~bbeckage/Teaching/PBIO_294/Manuals/manual.jags.pdf) for `pow(x, z)`.

So supporting real-valued exponents would require a constraint that the base is positive. That's probably too complicated for now :-)
