### ISSUE TITLE
More articles

### ISSUE THREAD

**Issue by lindeloev** [lindeloev/mcp#46]
- [x] Model comparison (once bridgesampling is implemented)
 - [ ] Bernoulli (merge with binomial?)
 - [x] Model diagnostics.
 - [x] Comparison to other packages: `changepoint`, `ecp`, `bcp`, `segmented`, `strucchange`, `tsmcp`, `robts:changerob`.
         Some of these are superior when it comes to speed (at the cost of accurate posteriors) and unsupervised change point detection.

**Comment by leungi** [comment]
The newly added docs really help a newbie like me! 👏 

Suggestion on the following (reference excerpt below):

- with `~ time`, the _intercept is implicit_; would it be more clear in the print method for `summary()` to show it as `##    score ~ 1 ~ 1 + time `?

```r
library(mcp)
segments = list(
  score ~ 1,  # intercept
  score ~ 1 ~ 0 + time,  # joined slope
  ~ time  # disjoined slope. The intercept is implicit when not 0 + x.
)

# Interpret, but do not sample.
fit = mcp(segments, sample = FALSE)
summary(fit)
```

**Comment by lindeloev** [comment]
Yes, that's a good idea! Will integrate with #42
