### ISSUE TITLE
Observation weights

### ISSUE THREAD

**Issue by mschubert** [lindeloev/mcp#77]
I have got a list of observations along a spatial axis, that I would like to fit a simple intercept model to (as described [here](https://github.com/lindeloev/mcp#at-a-glance)).

However, I am not equally confident in all of my observations, so I would like to add `weights` to account for uncertainty. I could do this for instance with `ecp::e.divisive`. 

Is this something you are considering for `mcp` as well?

Otherwise, there is of course the possibility to explicitly model the generative process in `JAGS`, but that would remove the convenience of `mcp`.

**Comment by lindeloev** [comment]
Yes, `mcp` should support weights but does not currently. I will implement this as in `brms`:

    y | weights(weight_col) ~ ...

For binomial, it would be 
    y | trials(N_col) + weights(weight_col) ~ ...

Under the hood, this will simply multiply the likelihood with `weight_col`, e.g. in pseudo-JAGS-code: `y[i] ~ weights_col[i] * dbin(y_, N_col)`

**Comment by lindeloev** [comment]
I just added weights for `family = gaussian()`. Do you need it for other families as well and would you mind testing it out?

It's in the development release. Install using:

    devtools::install_github("lindeloev/mcp")

I hope to submit it to CRAN within a few days.

**Comment by lindeloev** [comment]
`mcp` 0.3 is published on CRAN now, including support for weights.
