### ISSUE TITLE
Function to return posterior draws/lines displayed by `plot.mcpfit`

### ISSUE THREAD

**Issue by skgrange** [lindeloev/mcp#79]
Hello Jonas Kristoffer Lindeløv,
Great work on a package which serves a very good purpose which I am sure will see plenty of uptake. This is a question. I would like to extract the data behind the posterior draws/lines in the `plot.mcpfit` function. Is there user exposed function which can create these data by passing the `mcpfit` object and a few arguments? Many thanks,
Stuart.

**Comment by skgrange** [comment]
Hello,
Great stuff! Thanks a lot for the help. I have adapted things for my usage case and all is well. I will let you know if I can offer any ideas on the framework in the future. Enjoy the day!

**Comment by lindeloev** [comment]
This is now implemented via `fitted(fit)` and `predict(fit)` in the upcoming release. Sneek peak using:

    devtools::install_github("lindeloev/mcp")

Feedback most welcome!

**Comment by lindeloev** [comment]
`mcp` 0.3 is published on CRAN now, including these functions.
