### ISSUE TITLE
options to print summary 

### ISSUE THREAD

**Issue by frank0434** [lindeloev/mcp#97]
Wondering if it is possible to have a switch argument to turn off the direct `print` from `summary(fit)`?

https://github.com/lindeloev/mcp/blob/ce4c50ff85bd3552539124cc9b15db8cbba163ce/R/mcpfit_methods.R#L159
https://github.com/lindeloev/mcp/blob/ce4c50ff85bd3552539124cc9b15db8cbba163ce/R/mcpfit_methods.R#L243

Thank you

**Comment by lindeloev** [comment]
Would this add anything over and above calling `fixef(fit)`?

My impression is that `print`/`cat` are quite common in `summary()` methods.

**Comment by frank0434** [comment]
Thanks for the prompt reply, @lindeloev 
Pardon my ignorance. I didn't know the `fixef` was the solution I was after. 

Close the issue.
